### ISSUE TITLE
Prepare a set of issue templates for the R data package publication process

### ISSUE THREAD

**Issue by larnsce** [openwashdata/washr#2]
### Issue templates for
- [ ] naming of the package (example: https://github.com/openwashdata/data/issues/4#issuecomment-1471599970)
- [ ] submission of raw data (example: https://github.com/openwashdata/cbssuitabilityhaiti/issues/1)
- [ ] preparation of content for DESCRIPTION file
- [ ] documentation of variables in in dictionary.csv (example: https://github.com/openwashdata/cbssuitabilityhaiti/issues/2)
- [ ] content for README.rmd
- [ ] content for Vignette with some example visualisations

**Comment by bonschorno** [comment]
Can I close this, @larnsce?

**Comment by larnsce** [comment]
No. :)  

It's related to getting started with GitHub: https://openwashdata.org/pages/blog/posts/2024-05-17-data-publication-1/

**Comment by larnsce** [comment]
@massarin: adding you here. All of this might become irrelevant with your concept of a one-function publish process.

**Comment by massarin** [comment]
Yes, {fairenough} will provide templates that will be used internally by the program in an automated way. Of course this means that if the user would like to change DESCRIPTION, readme.md, dictionary.csv, etc.. after having used {fairenough}, they are free to do so.
